require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RoutersController do

  # This should return the minimal set of attributes required to create a valid
  # Router. As you add validations to Router, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "mac" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RoutersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all routers as @routers" do
      router = Router.create! valid_attributes
      get :index, {}, valid_session
      assigns(:routers).should eq([router])
    end
  end

  describe "GET show" do
    it "assigns the requested router as @router" do
      router = Router.create! valid_attributes
      get :show, {:id => router.to_param}, valid_session
      assigns(:router).should eq(router)
    end
  end

  describe "GET new" do
    it "assigns a new router as @router" do
      get :new, {}, valid_session
      assigns(:router).should be_a_new(Router)
    end
  end

  describe "GET edit" do
    it "assigns the requested router as @router" do
      router = Router.create! valid_attributes
      get :edit, {:id => router.to_param}, valid_session
      assigns(:router).should eq(router)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Router" do
        expect {
          post :create, {:router => valid_attributes}, valid_session
        }.to change(Router, :count).by(1)
      end

      it "assigns a newly created router as @router" do
        post :create, {:router => valid_attributes}, valid_session
        assigns(:router).should be_a(Router)
        assigns(:router).should be_persisted
      end

      it "redirects to the created router" do
        post :create, {:router => valid_attributes}, valid_session
        response.should redirect_to(Router.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved router as @router" do
        # Trigger the behavior that occurs when invalid params are submitted
        Router.any_instance.stub(:save).and_return(false)
        post :create, {:router => { "mac" => "invalid value" }}, valid_session
        assigns(:router).should be_a_new(Router)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Router.any_instance.stub(:save).and_return(false)
        post :create, {:router => { "mac" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested router" do
        router = Router.create! valid_attributes
        # Assuming there are no other routers in the database, this
        # specifies that the Router created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Router.any_instance.should_receive(:update).with({ "mac" => "MyString" })
        put :update, {:id => router.to_param, :router => { "mac" => "MyString" }}, valid_session
      end

      it "assigns the requested router as @router" do
        router = Router.create! valid_attributes
        put :update, {:id => router.to_param, :router => valid_attributes}, valid_session
        assigns(:router).should eq(router)
      end

      it "redirects to the router" do
        router = Router.create! valid_attributes
        put :update, {:id => router.to_param, :router => valid_attributes}, valid_session
        response.should redirect_to(router)
      end
    end

    describe "with invalid params" do
      it "assigns the router as @router" do
        router = Router.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Router.any_instance.stub(:save).and_return(false)
        put :update, {:id => router.to_param, :router => { "mac" => "invalid value" }}, valid_session
        assigns(:router).should eq(router)
      end

      it "re-renders the 'edit' template" do
        router = Router.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Router.any_instance.stub(:save).and_return(false)
        put :update, {:id => router.to_param, :router => { "mac" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested router" do
      router = Router.create! valid_attributes
      expect {
        delete :destroy, {:id => router.to_param}, valid_session
      }.to change(Router, :count).by(-1)
    end

    it "redirects to the routers list" do
      router = Router.create! valid_attributes
      delete :destroy, {:id => router.to_param}, valid_session
      response.should redirect_to(routers_url)
    end
  end

end
